sudo cp /src/syslinux/bios/com32/elflink/ldlinux/ldlinux.c32 /tftpboot/pxelinux/ldlinux.c32
sudo cp /src/syslinux/efi32/efi/syslinux.efi /tftpboot/pxelinux/bootia32.efi
sudo cp /src/syslinux/efi64/efi/syslinux.efi /tftpboot/pxelinux/bootia64.efi
sudo cp /src/syslinux/efi32/com32/elflink/ldlinux/ldlinux.e32 /tftpboot/pxelinux/ldlinux.e32
sudo cp /src/syslinux/efi64/com32/elflink/ldlinux/ldlinux.e64 /tftpboot/pxelinux/ldlinux.e64
sudo cp /src/syslinux/bios/com32/modules/linux.c32 /tftpboot/pxelinux/linux.c32
sudo cp /src/syslinux/bios/core/lpxelinux.0 /tftpboot/pxelinux/lpxelinux.0
sudo cp /src/syslinux/bios/core/pxelinux.0 /tftpboot/pxelinux/pxelinux.0
sudo cp /src/syslinux/bios/com32/chain/chain.c32 /tftpboot/pxelinux/bios/chain.c32
sudo cp /src/syslinux/efi32/com32/chain/chain.c32 /tftpboot/pxelinux/efi32/chain.c32
sudo cp /src/syslinux/efi64/com32/chain/chain.c32 /tftpboot/pxelinux/efi64/chain.c32
sudo cp /src/syslinux/bios/com32/hdt/hdt.c32 /tftpboot/pxelinux/bios/hdt.c32
sudo cp /src/syslinux/efi32/com32/hdt/hdt.c32 /tftpboot/pxelinux/efi32/hdt.c32
sudo cp /src/syslinux/efi64/com32/hdt/hdt.c32 /tftpboot/pxelinux/efi64/hdt.c32
sudo cp /src/syslinux/bios/com32/lib/libcom32.c32 /tftpboot/pxelinux/bios/libcom32.c32
sudo cp /src/syslinux/efi32/com32/lib/libcom32.c32 /tftpboot/pxelinux/efi32/libcom32.c32
sudo cp /src/syslinux/efi64/com32/lib/libcom32.c32 /tftpboot/pxelinux/efi64/libcom32.c32
sudo cp /src/syslinux/bios/com32/libutil/libutil.c32 /tftpboot/pxelinux/bios/libutil.c32
sudo cp /src/syslinux/efi32/com32/libutil/libutil.c32 /tftpboot/pxelinux/efi32/libutil.c32
sudo cp /src/syslinux/efi64/com32/libutil/libutil.c32 /tftpboot/pxelinux/efi64/libutil.c32
sudo cp /src/syslinux/bios/com32/menu/menu.c32 /tftpboot/pxelinux/bios/menu.c32
sudo cp /src/syslinux/efi32/com32/menu/menu.c32 /tftpboot/pxelinux/efi32/menu.c32
sudo cp /src/syslinux/efi64/com32/menu/menu.c32 /tftpboot/pxelinux/efi64/menu.c32
sudo cp /src/syslinux/bios/com32/modules/poweroff.c32 /tftpboot/pxelinux/bios/poweroff.c32
sudo cp /src/syslinux/bios/com32/modules/poweroff.c32 /tftpboot/pxelinux/efi32/poweroff.c32
sudo cp /src/syslinux/bios/com32/modules/poweroff.c32 /tftpboot/pxelinux/efi64/poweroff.c32
sudo cp /src/syslinux/bios/com32/modules/pxechn.c32 /tftpboot/pxelinux/bios/pxechn.c32
sudo cp /src/syslinux/bios/com32/modules/pxechn.c32 /tftpboot/pxelinux/efi32/pxechn.c32
sudo cp /src/syslinux/bios/com32/modules/pxechn.c32 /tftpboot/pxelinux/efi64/pxechn.c32
sudo cp /src/syslinux/bios/com32/menu/vesamenu.c32 /tftpboot/pxelinux/bios/vesamenu.c32
sudo cp /src/syslinux/efi32/com32/menu/vesamenu.c32 /tftpboot/pxelinux/efi32/vesamenu.c32
sudo cp /src/syslinux/efi64/com32/menu/vesamenu.c32 /tftpboot/pxelinux/efi64/vesamenu.c32
